const memberOrdering = {
  memberTypes: [
    // Index signature
    'signature',

    // Fields
    'public-static-field',
    'protected-static-field',
    'private-static-field',

    'public-decorated-field',
    'protected-decorated-field',
    'private-decorated-field',

    'public-instance-field',
    'protected-instance-field',
    'private-instance-field',

    'public-abstract-field',
    'protected-abstract-field',
    'private-abstract-field',

    'public-field',
    'protected-field',
    'private-field',

    'static-field',
    'instance-field',
    'abstract-field',

    'decorated-field',

    'field',

    // Constructors
    'public-constructor',
    'protected-constructor',
    'private-constructor',

    'constructor',

    // Methods
    'public-static-method',
    'protected-static-method',
    'private-static-method',

    'public-decorated-method',
    'protected-decorated-method',
    'private-decorated-method',

    'public-instance-method',
    'protected-instance-method',
    'private-instance-method',

    'public-abstract-method',
    'protected-abstract-method',
    'private-abstract-method',

    'public-method',
    'protected-method',
    'private-method',

    'static-method',
    'instance-method',
    'abstract-method',

    'decorated-method',

    'method',
  ],
  order: 'alphabetically',
};

module.exports = {
  rules: {
    // typescript-eslint rules
    '@typescript-eslint/array-type': 2,
    '@typescript-eslint/ban-ts-comment': [ 2, { 'ts-ignore': 'allow-with-description' } ],
    '@typescript-eslint/ban-tslint-comment': 2,
    '@typescript-eslint/consistent-indexed-object-style': 0,
    '@typescript-eslint/explicit-module-boundary-types': 0,
    '@typescript-eslint/member-delimiter-style': [
      2,
      {
        multiline: { delimiter: 'semi', requireLast: true },
        singleline: { delimiter: 'semi', requireLast: false },
      },
    ],
    '@typescript-eslint/member-ordering': [ 2, { default: memberOrdering } ],
    '@typescript-eslint/no-explicit-any': 0,
    // Extension rules
    '@typescript-eslint/brace-style': [ 2, '1tbs', { allowSingleLine: false } ],
    '@typescript-eslint/comma-dangle': [ 2, 'always-multiline' ],
    '@typescript-eslint/comma-spacing': 2,
    '@typescript-eslint/func-call-spacing': 2,
    '@typescript-eslint/indent': [ 2, 2 ],
    '@typescript-eslint/keyword-spacing': 2,
    '@typescript-eslint/lines-between-class-members': 0,
    '@typescript-eslint/no-array-constructor': 2,
    '@typescript-eslint/no-dupe-class-members': 2,
    '@typescript-eslint/no-duplicate-imports': 2,
    '@typescript-eslint/no-empty-function': 1,
    '@typescript-eslint/no-extra-parens': [
      2,
      'all',
      {
        conditionalAssign: false,
        returnAssign: false,
        nestedBinaryExpressions: false,
      },
    ],
    '@typescript-eslint/no-extra-semi': 2,
    '@typescript-eslint/no-invalid-this': 2,
    '@typescript-eslint/no-loss-of-precision': 2,
    '@typescript-eslint/no-shadow': 2,
    '@typescript-eslint/no-unused-expressions': [ 2, { allowShortCircuit: true, allowTernary: true } ],
    '@typescript-eslint/no-unused-vars': 2,
    '@typescript-eslint/no-useless-constructor': 1,
    '@typescript-eslint/quotes': [ 2, 'single' ], // poll
    '@typescript-eslint/semi': 2,
    '@typescript-eslint/space-before-function-paren': [
      2,
      {
        anonymous: 'always',
        named: 'never',
        asyncArrow: 'always',
      },
    ],
    '@typescript-eslint/space-infix-ops': 2,

    // Default eslint configs
    'no-template-curly-in-string': 1,
    'no-unreachable-loop': 1,
    'no-unsafe-optional-chaining': 2,
    'no-useless-backreference': 1,
    'require-atomic-updates': 1,
    'array-callback-return': 2,
    'block-scoped-var': 1,
    'curly': [ 2, 'multi-or-nest', 'consistent' ],
    'default-case': 2,
    'dot-location': [ 2, 'property' ],
    'eqeqeq': 2,
    'guard-for-in': 1,
    'max-classes-per-file': [ 2, 1 ],
    'no-else-return': 2,
    'no-floating-decimal': 2,
    'no-multi-spaces': 2,
    'no-new': 1,
    'no-new-func': 2,
    'no-new-wrappers': 2,
    'no-self-compare': 2,
    'no-useless-concat': 2,
    'no-useless-return': 2,
    'prefer-promise-reject-errors': 2,
    'radix': [ 2, 'as-needed' ],
    'require-await': 2,
    'no-undef': 0,
    'no-undef-init': 2,
    'no-undefined': 0,
    'array-bracket-newline': [ 2, { multiline: true } ],
    'array-bracket-spacing': [ 2, 'always' ],
    'array-element-newline': [ 2, 'consistent' ],
    'block-spacing': 2,
    'comma-style': 2,
    'computed-property-spacing': 2,
    'eol-last': 2,
    'function-call-argument-newline': [ 2, 'consistent' ],
    'key-spacing': 2,
    'linebreak-style': 2,
    'multiline-ternary': [ 2, 'always-multiline' ],
    'no-lonely-if': 2,
    'no-mixed-operators': [ 2, { allowSamePrecedence: true } ],
    'no-multiple-empty-lines': [ 2, { max: 2, maxEOF: 0, maxBOF: 0 } ],
    'no-new-object': 2,
    'no-trailing-spaces': 2,
    'no-unneeded-ternary': 2,
    'no-whitespace-before-property': 2,
    'nonblock-statement-body-position': 2,
    'object-curly-newline': [ 2, { multiline: true } ],
    'object-curly-spacing': [ 2, 'always' ],
    'operator-linebreak': [ 2, 'before' ],
    'padded-blocks': [ 2, 'never' ],
    'prefer-exponentiation-operator': 2,
    'prefer-object-spread': 2,
    'quote-props': [ 2, 'consistent-as-needed' ],
    'semi-spacing': 2,
    'semi-style': 2,
    'space-before-blocks': 2,
    'switch-colon-spacing': 2,
    'arrow-parens': 2,
    'arrow-spacing': 2,
    'no-useless-computed-key': 2,
    'no-var': 2,
    'prefer-template': 2,
    'rest-spread-spacing': 2,
    'template-curly-spacing': 2,

    // typescript-eslint conflicts
    'no-constant-condition': 0,
    'brace-style': 0,
    'comma-dangle': 0,
    'comma-spacing': 0,
    'default-param-last': 0,
    'dot-notation': 0,
    'func-call-spacing': 0,
    'indent': 0,
    'init-declarations': 0,
    'keyword-spacing': 0,
    'lines-between-class-members': 0,
    'no-array-constructor': 0,
    'no-dupe-class-members': 0,
    'no-duplicate-imports': 0,
    'no-empty-function': 0,
    'no-extra-parens': 0,
    'no-extra-semi': 0,
    'no-implied=eval': 0,
    'no-invalid-this': 0,
    'no-loop-func': 0,
    'no-loss-of-precision': 0,
    'no-magic-numbers': 0,
    'no-redeclare': 0,
    'no-return-await': 0,
    'no-shadow': 0,
    'no-throw-literal': 0,
    'no-unused-expressions': 0,
    'no-unused-vars': 0,
    'no-use-before-define': 0,
    'no-useless-constructor': 0,
    'quotes': 0,
    'semi': 0,
    'space-before-function-paren': 0,
    'space-infix-ops': 0,
  },
  plugins: [ '@typescript-eslint' ],
  extends: [ 'plugin:@typescript-eslint/recommended', 'eslint:recommended' ],
};
